import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/loginpage">LoginPage</Link>
        </li>
        <li>
          <Link to="/">LoginorSignupPage</Link>
        </li>
        <li>
          <Link to="/salesdetailspage">SalesDetailsPage</Link>
        </li>
        <li>
          <Link to="/forgotpasswordpagetwo">ForgotPasswordPageTwo</Link>
        </li>
        <li>
          <Link to="/forgotpasswordpagethree">ForgotPasswordPageThree</Link>
        </li>
        <li>
          <Link to="/signuppage">SignupPage</Link>
        </li>
        <li>
          <Link to="/forgotpasswordpageone">ForgotPasswordPageOne</Link>
        </li>
        <li>
          <Link to="/forgotpasswordpagefour">ForgotPasswordPageFour</Link>
        </li>
        <li>
          <Link to="/dashboardoverviewpage">DashboardOverviewPage</Link>
        </li>
        <li>
          <Link to="/productlistpage">ProductListPage</Link>
        </li>
        <li>
          <Link to="/customerlistpage">CustomerListPage</Link>
        </li>
        <li>
          <Link to="/singleproductpage">SingleProductPage</Link>
        </li>
        <li>
          <Link to="/mycartpage">MyCartPage</Link>
        </li>
        <li>
          <Link to="/checkoutaddresspage">CheckoutAddressPage</Link>
        </li>
        <li>
          <Link to="/checkoutshippingpage">CheckoutShippingPage</Link>
        </li>
        <li>
          <Link to="/checkoutpaymentpage">CheckoutPaymentPage</Link>
        </li>
        <li>
          <Link to="/customersupportpage">CustomerSupportPage</Link>
        </li>
        <li>
          <Link to="/customersupportchatpage">CustomerSupportChatPage</Link>
        </li>
        <li>
          <Link to="/footer">Footer</Link>
        </li>
        <li>
          <Link to="/wishlistpage">WishListPage</Link>
        </li>
        <li>
          <Link to="/landingpage">LandingPage</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
